"""Add is_ai_generated to quizzes

Revision ID: 93eb444bdeea
Revises: df6592190732
Create Date: 2026-02-26 02:52:26.307262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eb444bdeea'
down_revision = 'df6592190732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('is_ai_generated')

    # ### end Alembic commands ###
