"""add ai_model_usage table

Revision ID: a5b6bc09bc1e
Revises: d057821f326f
Create Date: 2026-02-26 02:02:28.126223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b6bc09bc1e'
down_revision = 'd057821f326f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'date', name='uq_model_date')
    )
    with op.batch_alter_table('ai_model_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_model_usage_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_model_usage_model_name'), ['model_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_model_usage_model_name'))
        batch_op.drop_index(batch_op.f('ix_ai_model_usage_date'))

    op.drop_table('ai_model_usage')
    # ### end Alembic commands ###
