"""fix ai_usage default values

Revision ID: df6592190732
Revises: a5b6bc09bc1e
Create Date: 2026-02-26 02:15:47.076118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6592190732'
down_revision = 'a5b6bc09bc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model_usage', schema=None) as batch_op:
        batch_op.alter_column('success_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('failure_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model_usage', schema=None) as batch_op:
        batch_op.alter_column('failure_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('success_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
